"""Blog aad

Revision ID: b71e7c9569f8
Revises: 5864fcca04ba
Create Date: 2018-09-17 10:00:48.315062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71e7c9569f8'
down_revision = '5864fcca04ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'time')
    # ### end Alembic commands ###
